"""
Knowledge Graph JSON을 Cypher 쿼리로 변환하는 유틸리티

JSON 형식의 Knowledge Graph를 Neo4j/Memgraph용 Cypher 쿼리로 변환합니다.
"""

import json
from pathlib import Path
from typing import Dict, Any, List, Optional
import re


class KGToCypherConverter:
    """Knowledge Graph JSON → Cypher 변환기"""

    def __init__(self):
        self.node_id_to_var = {}  # 노드 ID를 Cypher 변수명으로 매핑
        self.created_nodes = set()  # 생성된 노드 추적

    def convert_file(
        self,
        json_file_path: str,
        output_file_path: Optional[str] = None,
        clear_db: bool = False,
        create_indexes: bool = True
    ) -> str:
        """JSON 파일을 읽어 Cypher로 변환

        Args:
            json_file_path: 입력 JSON 파일 경로
            output_file_path: 출력 Cypher 파일 경로 (None이면 자동 생성)
            clear_db: 변환 전 데이터베이스 초기화 여부
            create_indexes: 인덱스 생성 쿼리 포함 여부

        Returns:
            생성된 Cypher 쿼리 문자열
        """
        # JSON 파일 읽기
        with open(json_file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)

        # Cypher 생성
        cypher = self.convert(data, clear_db=clear_db, create_indexes=create_indexes)

        # 출력 파일 경로 결정
        if output_file_path is None:
            json_path = Path(json_file_path)
            output_file_path = json_path.parent / f"{json_path.stem}.cypher"

        # 파일 저장
        with open(output_file_path, 'w', encoding='utf-8') as f:
            f.write(cypher)

        print(f"✅ Cypher 파일 생성 완료: {output_file_path}")
        return cypher

    def convert(
        self,
        kg_data: Dict[str, Any],
        clear_db: bool = False,
        create_indexes: bool = True
    ) -> str:
        """Knowledge Graph JSON을 Cypher 쿼리로 변환

        Args:
            kg_data: Knowledge Graph JSON 데이터
            clear_db: 데이터베이스 초기화 쿼리 포함 여부
            create_indexes: 인덱스 생성 쿼리 포함 여부

        Returns:
            Cypher 쿼리 문자열
        """
        cypher_lines = []

        # 헤더
        cypher_lines.append("// Knowledge Graph Import Script")
        cypher_lines.append("// Generated by KGToCypherConverter")
        cypher_lines.append("")

        # 데이터베이스 초기화
        if clear_db:
            cypher_lines.append("// Clear database")
            cypher_lines.append("MATCH (n) DETACH DELETE n;")
            cypher_lines.append("")

        # 인덱스 생성
        if create_indexes:
            cypher_lines.extend(self._generate_indexes(kg_data))
            cypher_lines.append("")

        # 그래프 데이터 추출
        graph = kg_data.get("graph", kg_data)
        nodes = graph.get("nodes", graph.get("entities", []))
        edges = graph.get("edges", graph.get("relationships", []))

        # 노드 생성
        cypher_lines.append("// ==================== Create Nodes ====================")
        cypher_lines.append("")
        node_queries = self._generate_node_queries(nodes)
        cypher_lines.extend(node_queries)
        cypher_lines.append("")

        # 관계 생성
        cypher_lines.append("// ==================== Create Relationships ====================")
        cypher_lines.append("")
        rel_queries = self._generate_relationship_queries(edges)
        cypher_lines.extend(rel_queries)
        cypher_lines.append("")

        # 메타데이터 추가 (선택적)
        if "metadata" in kg_data:
            cypher_lines.append("// ==================== Add Metadata ====================")
            cypher_lines.append("")
            metadata_queries = self._generate_metadata_queries(kg_data["metadata"])
            cypher_lines.extend(metadata_queries)
            cypher_lines.append("")

        # 통계
        cypher_lines.append("// ==================== Statistics ====================")
        cypher_lines.append(f"// Total Nodes: {len(nodes)}")
        cypher_lines.append(f"// Total Relationships: {len(edges)}")

        return "\n".join(cypher_lines)

    def _generate_indexes(self, kg_data: Dict[str, Any]) -> List[str]:
        """인덱스 생성 쿼리 생성"""
        queries = ["// Create indexes for performance"]

        # 엔티티 타입별 인덱스 생성
        graph = kg_data.get("graph", kg_data)
        nodes = graph.get("nodes", graph.get("entities", []))

        entity_types = set()
        for node in nodes:
            node_type = node.get("type", "Unknown")
            entity_types.add(node_type)

        for entity_type in sorted(entity_types):
            # Neo4j/Memgraph 스타일 인덱스
            queries.append(f"CREATE INDEX IF NOT EXISTS FOR (n:{entity_type}) ON (n.id);")
            queries.append(f"CREATE INDEX IF NOT EXISTS FOR (n:{entity_type}) ON (n.name);")

        return queries

    def _generate_node_queries(self, nodes: List[Dict[str, Any]]) -> List[str]:
        """노드 생성 쿼리 생성"""
        queries = []

        for i, node in enumerate(nodes):
            node_id = node.get("id", f"node_{i}")
            node_type = node.get("type", "Unknown")
            properties = node.get("properties", {})

            # Cypher 변수명 생성 (알파벳+숫자만)
            var_name = self._sanitize_var_name(node_id)
            self.node_id_to_var[node_id] = var_name

            # 프로퍼티 문자열 생성
            props = {"id": node_id}
            props.update(properties)

            props_str = self._format_properties(props)

            # CREATE 쿼리 생성
            query = f"CREATE ({var_name}:{node_type} {props_str});"
            queries.append(query)

            self.created_nodes.add(node_id)

        return queries

    def _generate_relationship_queries(self, edges: List[Dict[str, Any]]) -> List[str]:
        """관계 생성 쿼리 생성"""
        queries = []

        for i, edge in enumerate(edges):
            edge_id = edge.get("id", f"edge_{i}")
            source_id = edge.get("source")
            target_id = edge.get("target")
            rel_type = edge.get("type", "RELATED_TO")
            properties = edge.get("properties", {})

            # 소스/타겟 노드가 생성되었는지 확인
            if source_id not in self.created_nodes:
                queries.append(f"// Warning: Source node not found: {source_id}")
                continue
            if target_id not in self.created_nodes:
                queries.append(f"// Warning: Target node not found: {target_id}")
                continue

            # 변수명 가져오기
            source_var = self.node_id_to_var.get(source_id, f"src_{i}")
            target_var = self.node_id_to_var.get(target_id, f"tgt_{i}")

            # 프로퍼티 문자열 생성
            props = {"id": edge_id}
            props.update(properties)

            if props:
                props_str = " " + self._format_properties(props)
            else:
                props_str = ""

            # MATCH + CREATE 쿼리 생성
            query = (
                f"MATCH ({source_var} {{id: '{source_id}'}}), "
                f"({target_var} {{id: '{target_id}'}}) "
                f"CREATE ({source_var})-[:{rel_type}{props_str}]->({target_var});"
            )
            queries.append(query)

        return queries

    def _generate_metadata_queries(self, metadata: Dict[str, Any]) -> List[str]:
        """메타데이터 노드 생성 쿼리"""
        queries = []

        # 메타데이터를 별도 노드로 생성
        props_str = self._format_properties(metadata)
        queries.append(f"CREATE (meta:Metadata {props_str});")

        return queries

    def _sanitize_var_name(self, node_id: str) -> str:
        """노드 ID를 Cypher 변수명으로 변환"""
        # 알파벳, 숫자, 언더스코어만 허용
        sanitized = re.sub(r'[^a-zA-Z0-9_]', '_', node_id)
        # 숫자로 시작하면 앞에 'n' 추가
        if sanitized and sanitized[0].isdigit():
            sanitized = 'n' + sanitized
        return sanitized or 'node'

    def _format_properties(self, properties: Dict[str, Any]) -> str:
        """프로퍼티를 Cypher 형식으로 포맷"""
        if not properties:
            return "{}"

        prop_parts = []
        for key, value in properties.items():
            # 키 sanitize
            safe_key = re.sub(r'[^a-zA-Z0-9_]', '_', key)

            # 값 포맷
            if isinstance(value, str):
                # 문자열 이스케이프
                escaped = value.replace("\\", "\\\\").replace("'", "\\'").replace('"', '\\"')
                prop_parts.append(f"{safe_key}: '{escaped}'")
            elif isinstance(value, bool):
                prop_parts.append(f"{safe_key}: {str(value).lower()}")
            elif isinstance(value, (int, float)):
                prop_parts.append(f"{safe_key}: {value}")
            elif value is None:
                prop_parts.append(f"{safe_key}: null")
            elif isinstance(value, (list, dict)):
                # 복잡한 타입은 JSON 문자열로 변환
                json_str = json.dumps(value, ensure_ascii=False)
                escaped = json_str.replace("\\", "\\\\").replace("'", "\\'")
                prop_parts.append(f"{safe_key}: '{escaped}'")
            else:
                # 기타 타입은 문자열로 변환
                prop_parts.append(f"{safe_key}: '{str(value)}'")

        return "{" + ", ".join(prop_parts) + "}"


def convert_kg_json_to_cypher(
    json_file: str,
    output_file: Optional[str] = None,
    clear_db: bool = False,
    create_indexes: bool = True
) -> str:
    """Knowledge Graph JSON 파일을 Cypher로 변환하는 편의 함수

    Args:
        json_file: 입력 JSON 파일 경로
        output_file: 출력 Cypher 파일 경로 (None이면 자동)
        clear_db: 데이터베이스 초기화 포함 여부
        create_indexes: 인덱스 생성 포함 여부

    Returns:
        생성된 Cypher 쿼리 문자열
    """
    converter = KGToCypherConverter()
    return converter.convert_file(
        json_file,
        output_file,
        clear_db=clear_db,
        create_indexes=create_indexes
    )


if __name__ == "__main__":
    import sys

    # --help 처리
    if len(sys.argv) < 2 or '--help' in sys.argv or '-h' in sys.argv:
        print("Usage: python kg_to_cypher.py <json_file> [output_file] [--clear-db] [--no-indexes]")
        print()
        print("Arguments:")
        print("  json_file       입력 Knowledge Graph JSON 파일")
        print("  output_file     출력 Cypher 파일 (선택사항, 기본값: <json_file>.cypher)")
        print()
        print("Options:")
        print("  --clear-db      데이터베이스 초기화 쿼리 포함 (MATCH (n) DETACH DELETE n)")
        print("  --no-indexes    인덱스 생성 쿼리 제외")
        print("  -h, --help      이 도움말 표시")
        print()
        print("Examples:")
        print("  python kg_to_cypher.py knowledge_graph.json")
        print("  python kg_to_cypher.py knowledge_graph.json output.cypher")
        print("  python kg_to_cypher.py knowledge_graph.json --clear-db")
        print("  python kg_to_cypher.py knowledge_graph.json output.cypher --clear-db --no-indexes")
        sys.exit(0 if '--help' in sys.argv or '-h' in sys.argv else 1)

    json_file = sys.argv[1]
    output_file = sys.argv[2] if len(sys.argv) > 2 and not sys.argv[2].startswith('--') else None
    clear_db = '--clear-db' in sys.argv
    create_indexes = '--no-indexes' not in sys.argv

    print(f"📄 JSON 파일: {json_file}")
    print(f"📝 출력 파일: {output_file or '자동 생성'}")
    print(f"🗑️  DB 초기화: {clear_db}")
    print(f"📊 인덱스 생성: {create_indexes}")
    print()

    try:
        cypher = convert_kg_json_to_cypher(
            json_file,
            output_file,
            clear_db=clear_db,
            create_indexes=create_indexes
        )

        # 통계 출력
        node_count = cypher.count("CREATE (")
        rel_count = cypher.count("CREATE (") - cypher.count("CREATE (meta:")

        print(f"📊 생성된 쿼리:")
        print(f"   - 노드: {node_count}개")
        print(f"   - 관계: {rel_count}개")
        print(f"   - 총 라인: {len(cypher.splitlines())}줄")

    except Exception as e:
        print(f"❌ 오류: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
